#load "../Relations/Generator.Relations.Setup.fsx"
#load "../Relations/Stage3.Handmade.fs"
#load "../Relations/Stage3.Generated.fs"
#load "../Relations/Stage4.Handmade.fs"
#load "../Relations/Stage4.Generated.fs"